2017-12-02 00:45:39,711 (10412/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2017-12-02 00:45:39,724 (10412/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/1.8.1/libexec/lib/python2.7/site-packages/pgcli/main.py", line 389, in connect\n    raise e\nOperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2017-12-02 00:45:59,502 (10467/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2017-12-02 00:45:59,507 (10467/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/1.8.1/libexec/lib/python2.7/site-packages/pgcli/main.py", line 389, in connect\n    raise e\nOperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2017-12-02 00:47:07,920 (10630/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2017-12-02 00:47:07,938 (10630/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/1.8.1/libexec/lib/python2.7/site-packages/pgcli/main.py", line 389, in connect\n    raise e\nOperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2017-12-22 21:05:19,619 (73537/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2017-12-22 21:05:19,637 (73537/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/1.8.2/libexec/lib/python2.7/site-packages/pgcli/main.py", line 392, in connect\n    raise e\nOperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2017-12-24 02:09:07,655 (84571/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2017-12-24 02:09:07,684 (84571/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/1.8.2/libexec/lib/python2.7/site-packages/pgcli/main.py", line 392, in connect\n    raise e\nOperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
